import React from 'react'
import './HomeScreen.css'

function HomeScreen(){
    
    return(
        <div className='homeScreen'>
            <div className='header'>
                <h1> PáginaDeInicio</h1>
            </div>
            <div>
                <button>
                    Formulario
                </button>    
            </div>    
        </div>
    )
};

export default HomeScreen;